-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_GMEM_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_DATA_WIDTH : INTEGER := 256;
    C_M_AXI_GMEM_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_USER_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_PROT_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_CACHE_VALUE : INTEGER := 3 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC;
    m_axi_gmem_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_AWREADY : IN STD_LOGIC;
    m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_AWUSER_WIDTH-1 downto 0);
    m_axi_gmem_WVALID : OUT STD_LOGIC;
    m_axi_gmem_WREADY : IN STD_LOGIC;
    m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH/8-1 downto 0);
    m_axi_gmem_WLAST : OUT STD_LOGIC;
    m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_WUSER_WIDTH-1 downto 0);
    m_axi_gmem_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_ARREADY : IN STD_LOGIC;
    m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ARUSER_WIDTH-1 downto 0);
    m_axi_gmem_RVALID : IN STD_LOGIC;
    m_axi_gmem_RREADY : OUT STD_LOGIC;
    m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_RLAST : IN STD_LOGIC;
    m_axi_gmem_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_RUSER_WIDTH-1 downto 0);
    m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BVALID : IN STD_LOGIC;
    m_axi_gmem_BREADY : OUT STD_LOGIC;
    m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_BUSER_WIDTH-1 downto 0) );
end;


architecture behav of top is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "top_top,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu48dr-ffvg1517-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=3.650000,HLS_SYN_LAT=1659,HLS_SYN_TPT=576,HLS_SYN_MEM=35,HLS_SYN_DSP=0,HLS_SYN_FF=4370,HLS_SYN_LUT=7692,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant C_M_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv19_0 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv256_lc_1 : STD_LOGIC_VECTOR (255 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_rst_reg_2 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_2 : signal is "no";
    signal ap_rst_reg_1 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_1 : signal is "no";
    signal ap_rst_n_inv : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_n_inv : signal is "no";
    signal input_r_i_q0 : STD_LOGIC_VECTOR (16 downto 0);
    signal input_r_t_q0 : STD_LOGIC_VECTOR (16 downto 0);
    signal output_r_i_q0 : STD_LOGIC_VECTOR (18 downto 0);
    signal output_r_t_q0 : STD_LOGIC_VECTOR (18 downto 0);
    signal in_r : STD_LOGIC_VECTOR (63 downto 0);
    signal out_r : STD_LOGIC_VECTOR (63 downto 0);
    signal N : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_start : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_continue : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal gmem_0_AWREADY : STD_LOGIC;
    signal gmem_0_WREADY : STD_LOGIC;
    signal gmem_0_ARREADY : STD_LOGIC;
    signal gmem_0_RVALID : STD_LOGIC;
    signal gmem_0_RDATA : STD_LOGIC_VECTOR (255 downto 0);
    signal gmem_0_RLAST : STD_LOGIC;
    signal gmem_0_RID : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_0_RFIFONUM : STD_LOGIC_VECTOR (8 downto 0);
    signal gmem_0_RUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_0_RRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal gmem_0_BVALID : STD_LOGIC;
    signal gmem_0_BRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal gmem_0_BID : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_0_BUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal entry_proc_U0_ap_start : STD_LOGIC;
    signal entry_proc_U0_ap_done : STD_LOGIC;
    signal entry_proc_U0_ap_continue : STD_LOGIC;
    signal entry_proc_U0_ap_idle : STD_LOGIC;
    signal entry_proc_U0_ap_ready : STD_LOGIC;
    signal entry_proc_U0_out_r_c_din : STD_LOGIC_VECTOR (63 downto 0);
    signal entry_proc_U0_out_r_c_write : STD_LOGIC;
    signal read_task_U0_ap_start : STD_LOGIC;
    signal read_task_U0_ap_done : STD_LOGIC;
    signal read_task_U0_ap_continue : STD_LOGIC;
    signal read_task_U0_ap_idle : STD_LOGIC;
    signal read_task_U0_ap_ready : STD_LOGIC;
    signal read_task_U0_m_axi_gmem_0_AWVALID : STD_LOGIC;
    signal read_task_U0_m_axi_gmem_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal read_task_U0_m_axi_gmem_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal read_task_U0_m_axi_gmem_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal read_task_U0_m_axi_gmem_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal read_task_U0_m_axi_gmem_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal read_task_U0_m_axi_gmem_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal read_task_U0_m_axi_gmem_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal read_task_U0_m_axi_gmem_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal read_task_U0_m_axi_gmem_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal read_task_U0_m_axi_gmem_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal read_task_U0_m_axi_gmem_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal read_task_U0_m_axi_gmem_0_WVALID : STD_LOGIC;
    signal read_task_U0_m_axi_gmem_0_WDATA : STD_LOGIC_VECTOR (255 downto 0);
    signal read_task_U0_m_axi_gmem_0_WSTRB : STD_LOGIC_VECTOR (31 downto 0);
    signal read_task_U0_m_axi_gmem_0_WLAST : STD_LOGIC;
    signal read_task_U0_m_axi_gmem_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal read_task_U0_m_axi_gmem_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal read_task_U0_m_axi_gmem_0_ARVALID : STD_LOGIC;
    signal read_task_U0_m_axi_gmem_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal read_task_U0_m_axi_gmem_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal read_task_U0_m_axi_gmem_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal read_task_U0_m_axi_gmem_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal read_task_U0_m_axi_gmem_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal read_task_U0_m_axi_gmem_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal read_task_U0_m_axi_gmem_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal read_task_U0_m_axi_gmem_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal read_task_U0_m_axi_gmem_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal read_task_U0_m_axi_gmem_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal read_task_U0_m_axi_gmem_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal read_task_U0_m_axi_gmem_0_RREADY : STD_LOGIC;
    signal read_task_U0_m_axi_gmem_0_BREADY : STD_LOGIC;
    signal read_task_U0_input_r_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal read_task_U0_input_r_ce0 : STD_LOGIC;
    signal read_task_U0_input_r_we0 : STD_LOGIC;
    signal read_task_U0_input_r_d0 : STD_LOGIC_VECTOR (16 downto 0);
    signal read_task_U0_ap_return : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_channel_done_N_c1_channel : STD_LOGIC;
    signal N_c1_channel_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_N_c1_channel : STD_LOGIC := '0';
    signal ap_sync_channel_write_N_c1_channel : STD_LOGIC;
    signal ap_channel_done_input_r : STD_LOGIC;
    signal read_task_U0_input_r_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_input_r : STD_LOGIC := '0';
    signal ap_sync_channel_write_input_r : STD_LOGIC;
    signal fir_U0_ap_start : STD_LOGIC;
    signal fir_U0_ap_done : STD_LOGIC;
    signal fir_U0_ap_continue : STD_LOGIC;
    signal fir_U0_ap_idle : STD_LOGIC;
    signal fir_U0_ap_ready : STD_LOGIC;
    signal fir_U0_in_r_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal fir_U0_in_r_ce0 : STD_LOGIC;
    signal fir_U0_out_r_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal fir_U0_out_r_ce0 : STD_LOGIC;
    signal fir_U0_out_r_we0 : STD_LOGIC;
    signal fir_U0_out_r_d0 : STD_LOGIC_VECTOR (18 downto 0);
    signal fir_U0_ap_return : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_channel_done_N_c_channel : STD_LOGIC;
    signal N_c_channel_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_N_c_channel : STD_LOGIC := '0';
    signal ap_sync_channel_write_N_c_channel : STD_LOGIC;
    signal ap_channel_done_output_r : STD_LOGIC;
    signal fir_U0_out_r_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_output_r : STD_LOGIC := '0';
    signal ap_sync_channel_write_output_r : STD_LOGIC;
    signal write_task_U0_ap_start : STD_LOGIC;
    signal write_task_U0_ap_done : STD_LOGIC;
    signal write_task_U0_ap_continue : STD_LOGIC;
    signal write_task_U0_ap_idle : STD_LOGIC;
    signal write_task_U0_ap_ready : STD_LOGIC;
    signal write_task_U0_output_r_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal write_task_U0_output_r_ce0 : STD_LOGIC;
    signal write_task_U0_m_axi_gmem_0_AWVALID : STD_LOGIC;
    signal write_task_U0_m_axi_gmem_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal write_task_U0_m_axi_gmem_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal write_task_U0_m_axi_gmem_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal write_task_U0_m_axi_gmem_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal write_task_U0_m_axi_gmem_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal write_task_U0_m_axi_gmem_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal write_task_U0_m_axi_gmem_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal write_task_U0_m_axi_gmem_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal write_task_U0_m_axi_gmem_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal write_task_U0_m_axi_gmem_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal write_task_U0_m_axi_gmem_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal write_task_U0_m_axi_gmem_0_WVALID : STD_LOGIC;
    signal write_task_U0_m_axi_gmem_0_WDATA : STD_LOGIC_VECTOR (255 downto 0);
    signal write_task_U0_m_axi_gmem_0_WSTRB : STD_LOGIC_VECTOR (31 downto 0);
    signal write_task_U0_m_axi_gmem_0_WLAST : STD_LOGIC;
    signal write_task_U0_m_axi_gmem_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal write_task_U0_m_axi_gmem_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal write_task_U0_m_axi_gmem_0_ARVALID : STD_LOGIC;
    signal write_task_U0_m_axi_gmem_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal write_task_U0_m_axi_gmem_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal write_task_U0_m_axi_gmem_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal write_task_U0_m_axi_gmem_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal write_task_U0_m_axi_gmem_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal write_task_U0_m_axi_gmem_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal write_task_U0_m_axi_gmem_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal write_task_U0_m_axi_gmem_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal write_task_U0_m_axi_gmem_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal write_task_U0_m_axi_gmem_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal write_task_U0_m_axi_gmem_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal write_task_U0_m_axi_gmem_0_RREADY : STD_LOGIC;
    signal write_task_U0_m_axi_gmem_0_BREADY : STD_LOGIC;
    signal write_task_U0_out_r_read : STD_LOGIC;
    signal input_r_i_full_n : STD_LOGIC;
    signal input_r_t_empty_n : STD_LOGIC;
    signal output_r_i_full_n : STD_LOGIC;
    signal output_r_t_empty_n : STD_LOGIC;
    signal out_r_c_full_n : STD_LOGIC;
    signal out_r_c_dout : STD_LOGIC_VECTOR (63 downto 0);
    signal out_r_c_empty_n : STD_LOGIC;
    signal out_r_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal out_r_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal N_c1_channel_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal N_c1_channel_empty_n : STD_LOGIC;
    signal N_c1_channel_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal N_c1_channel_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal N_c_channel_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal N_c_channel_empty_n : STD_LOGIC;
    signal N_c_channel_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal N_c_channel_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_entry_proc_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_entry_proc_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_read_task_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_read_task_U0_ap_ready : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component top_entry_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        out_r : IN STD_LOGIC_VECTOR (63 downto 0);
        out_r_c_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        out_r_c_full_n : IN STD_LOGIC;
        out_r_c_write : OUT STD_LOGIC;
        out_r_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        out_r_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component top_read_task IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem_0_WREADY : IN STD_LOGIC;
        m_axi_gmem_0_WDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
        m_axi_gmem_0_WSTRB : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_RVALID : IN STD_LOGIC;
        m_axi_gmem_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem_0_RDATA : IN STD_LOGIC_VECTOR (255 downto 0);
        m_axi_gmem_0_RLAST : IN STD_LOGIC;
        m_axi_gmem_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_BVALID : IN STD_LOGIC;
        m_axi_gmem_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        in_r : IN STD_LOGIC_VECTOR (63 downto 0);
        input_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        input_r_ce0 : OUT STD_LOGIC;
        input_r_we0 : OUT STD_LOGIC;
        input_r_d0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        N : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component top_fir IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        in_r_ce0 : OUT STD_LOGIC;
        in_r_q0 : IN STD_LOGIC_VECTOR (16 downto 0);
        out_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        out_r_ce0 : OUT STD_LOGIC;
        out_r_we0 : OUT STD_LOGIC;
        out_r_d0 : OUT STD_LOGIC_VECTOR (18 downto 0);
        p_read : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component top_write_task IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        output_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        output_r_ce0 : OUT STD_LOGIC;
        output_r_q0 : IN STD_LOGIC_VECTOR (18 downto 0);
        m_axi_gmem_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem_0_WREADY : IN STD_LOGIC;
        m_axi_gmem_0_WDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
        m_axi_gmem_0_WSTRB : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_RVALID : IN STD_LOGIC;
        m_axi_gmem_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem_0_RDATA : IN STD_LOGIC_VECTOR (255 downto 0);
        m_axi_gmem_0_RLAST : IN STD_LOGIC;
        m_axi_gmem_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_BVALID : IN STD_LOGIC;
        m_axi_gmem_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        out_r_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        out_r_empty_n : IN STD_LOGIC;
        out_r_read : OUT STD_LOGIC;
        out_r_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        out_r_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        p_read : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component top_input_r_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        i_address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        i_ce0 : IN STD_LOGIC;
        i_we0 : IN STD_LOGIC;
        i_d0 : IN STD_LOGIC_VECTOR (16 downto 0);
        i_q0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        t_address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        t_ce0 : IN STD_LOGIC;
        t_we0 : IN STD_LOGIC;
        t_d0 : IN STD_LOGIC_VECTOR (16 downto 0);
        t_q0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        i_ce : IN STD_LOGIC;
        t_ce : IN STD_LOGIC;
        i_full_n : OUT STD_LOGIC;
        i_write : IN STD_LOGIC;
        t_empty_n : OUT STD_LOGIC;
        t_read : IN STD_LOGIC );
    end component;


    component top_output_r_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        i_address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        i_ce0 : IN STD_LOGIC;
        i_we0 : IN STD_LOGIC;
        i_d0 : IN STD_LOGIC_VECTOR (18 downto 0);
        i_q0 : OUT STD_LOGIC_VECTOR (18 downto 0);
        t_address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        t_ce0 : IN STD_LOGIC;
        t_we0 : IN STD_LOGIC;
        t_d0 : IN STD_LOGIC_VECTOR (18 downto 0);
        t_q0 : OUT STD_LOGIC_VECTOR (18 downto 0);
        i_ce : IN STD_LOGIC;
        t_ce : IN STD_LOGIC;
        i_full_n : OUT STD_LOGIC;
        i_write : IN STD_LOGIC;
        t_empty_n : OUT STD_LOGIC;
        t_read : IN STD_LOGIC );
    end component;


    component top_fifo_w64_d4_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (63 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (63 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component top_fifo_w32_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component top_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        in_r : OUT STD_LOGIC_VECTOR (63 downto 0);
        out_r : OUT STD_LOGIC_VECTOR (63 downto 0);
        N : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_continue : OUT STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component top_gmem_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        CH0_USER_RFIFONUM_WIDTH : INTEGER;
        CH0_USER_DW : INTEGER;
        CH0_USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_CH0_ARVALID : IN STD_LOGIC;
        I_CH0_ARREADY : OUT STD_LOGIC;
        I_CH0_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RVALID : OUT STD_LOGIC;
        I_CH0_RREADY : IN STD_LOGIC;
        I_CH0_RDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
        I_CH0_RFIFONUM : OUT STD_LOGIC_VECTOR (8 downto 0);
        I_CH0_AWVALID : IN STD_LOGIC;
        I_CH0_AWREADY : OUT STD_LOGIC;
        I_CH0_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WVALID : IN STD_LOGIC;
        I_CH0_WREADY : OUT STD_LOGIC;
        I_CH0_WDATA : IN STD_LOGIC_VECTOR (255 downto 0);
        I_CH0_WSTRB : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_BVALID : OUT STD_LOGIC;
        I_CH0_BREADY : IN STD_LOGIC );
    end component;



begin
    input_r_U : component top_input_r_RAM_AUTO_1R1W
    generic map (
        DataWidth => 17,
        AddressRange => 1000,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => read_task_U0_input_r_address0,
        i_ce0 => read_task_U0_input_r_ce0,
        i_we0 => read_task_U0_input_r_we0,
        i_d0 => read_task_U0_input_r_d0,
        i_q0 => input_r_i_q0,
        t_address0 => fir_U0_in_r_address0,
        t_ce0 => fir_U0_in_r_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv17_0,
        t_q0 => input_r_t_q0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => input_r_i_full_n,
        i_write => ap_channel_done_input_r,
        t_empty_n => input_r_t_empty_n,
        t_read => fir_U0_ap_ready);

    output_r_U : component top_output_r_RAM_AUTO_1R1W
    generic map (
        DataWidth => 19,
        AddressRange => 1000,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => fir_U0_out_r_address0,
        i_ce0 => fir_U0_out_r_ce0,
        i_we0 => fir_U0_out_r_we0,
        i_d0 => fir_U0_out_r_d0,
        i_q0 => output_r_i_q0,
        t_address0 => write_task_U0_output_r_address0,
        t_ce0 => write_task_U0_output_r_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv19_0,
        t_q0 => output_r_t_q0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => output_r_i_full_n,
        i_write => ap_channel_done_output_r,
        t_empty_n => output_r_t_empty_n,
        t_read => write_task_U0_ap_ready);

    control_s_axi_U : component top_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        in_r => in_r,
        out_r => out_r,
        N => N,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_continue => ap_continue,
        ap_idle => ap_idle);

    gmem_m_axi_U : component top_gmem_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 70,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_GMEM_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_GMEM_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_GMEM_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_GMEM_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_GMEM_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_GMEM_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_GMEM_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_GMEM_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_GMEM_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_GMEM_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_GMEM_CACHE_VALUE,
        CH0_USER_RFIFONUM_WIDTH => 9,
        CH0_USER_DW => 256,
        CH0_USER_AW => 64,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 16)
    port map (
        AWVALID => m_axi_gmem_AWVALID,
        AWREADY => m_axi_gmem_AWREADY,
        AWADDR => m_axi_gmem_AWADDR,
        AWID => m_axi_gmem_AWID,
        AWLEN => m_axi_gmem_AWLEN,
        AWSIZE => m_axi_gmem_AWSIZE,
        AWBURST => m_axi_gmem_AWBURST,
        AWLOCK => m_axi_gmem_AWLOCK,
        AWCACHE => m_axi_gmem_AWCACHE,
        AWPROT => m_axi_gmem_AWPROT,
        AWQOS => m_axi_gmem_AWQOS,
        AWREGION => m_axi_gmem_AWREGION,
        AWUSER => m_axi_gmem_AWUSER,
        WVALID => m_axi_gmem_WVALID,
        WREADY => m_axi_gmem_WREADY,
        WDATA => m_axi_gmem_WDATA,
        WSTRB => m_axi_gmem_WSTRB,
        WLAST => m_axi_gmem_WLAST,
        WID => m_axi_gmem_WID,
        WUSER => m_axi_gmem_WUSER,
        ARVALID => m_axi_gmem_ARVALID,
        ARREADY => m_axi_gmem_ARREADY,
        ARADDR => m_axi_gmem_ARADDR,
        ARID => m_axi_gmem_ARID,
        ARLEN => m_axi_gmem_ARLEN,
        ARSIZE => m_axi_gmem_ARSIZE,
        ARBURST => m_axi_gmem_ARBURST,
        ARLOCK => m_axi_gmem_ARLOCK,
        ARCACHE => m_axi_gmem_ARCACHE,
        ARPROT => m_axi_gmem_ARPROT,
        ARQOS => m_axi_gmem_ARQOS,
        ARREGION => m_axi_gmem_ARREGION,
        ARUSER => m_axi_gmem_ARUSER,
        RVALID => m_axi_gmem_RVALID,
        RREADY => m_axi_gmem_RREADY,
        RDATA => m_axi_gmem_RDATA,
        RLAST => m_axi_gmem_RLAST,
        RID => m_axi_gmem_RID,
        RUSER => m_axi_gmem_RUSER,
        RRESP => m_axi_gmem_RRESP,
        BVALID => m_axi_gmem_BVALID,
        BREADY => m_axi_gmem_BREADY,
        BRESP => m_axi_gmem_BRESP,
        BID => m_axi_gmem_BID,
        BUSER => m_axi_gmem_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_CH0_ARVALID => read_task_U0_m_axi_gmem_0_ARVALID,
        I_CH0_ARREADY => gmem_0_ARREADY,
        I_CH0_ARADDR => read_task_U0_m_axi_gmem_0_ARADDR,
        I_CH0_ARLEN => read_task_U0_m_axi_gmem_0_ARLEN,
        I_CH0_RVALID => gmem_0_RVALID,
        I_CH0_RREADY => read_task_U0_m_axi_gmem_0_RREADY,
        I_CH0_RDATA => gmem_0_RDATA,
        I_CH0_RFIFONUM => gmem_0_RFIFONUM,
        I_CH0_AWVALID => write_task_U0_m_axi_gmem_0_AWVALID,
        I_CH0_AWREADY => gmem_0_AWREADY,
        I_CH0_AWADDR => write_task_U0_m_axi_gmem_0_AWADDR,
        I_CH0_AWLEN => write_task_U0_m_axi_gmem_0_AWLEN,
        I_CH0_WVALID => write_task_U0_m_axi_gmem_0_WVALID,
        I_CH0_WREADY => gmem_0_WREADY,
        I_CH0_WDATA => write_task_U0_m_axi_gmem_0_WDATA,
        I_CH0_WSTRB => write_task_U0_m_axi_gmem_0_WSTRB,
        I_CH0_BVALID => gmem_0_BVALID,
        I_CH0_BREADY => write_task_U0_m_axi_gmem_0_BREADY);

    entry_proc_U0 : component top_entry_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => entry_proc_U0_ap_start,
        ap_done => entry_proc_U0_ap_done,
        ap_continue => entry_proc_U0_ap_continue,
        ap_idle => entry_proc_U0_ap_idle,
        ap_ready => entry_proc_U0_ap_ready,
        out_r => out_r,
        out_r_c_din => entry_proc_U0_out_r_c_din,
        out_r_c_full_n => out_r_c_full_n,
        out_r_c_write => entry_proc_U0_out_r_c_write,
        out_r_c_num_data_valid => out_r_c_num_data_valid,
        out_r_c_fifo_cap => out_r_c_fifo_cap);

    read_task_U0 : component top_read_task
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => read_task_U0_ap_start,
        ap_done => read_task_U0_ap_done,
        ap_continue => read_task_U0_ap_continue,
        ap_idle => read_task_U0_ap_idle,
        ap_ready => read_task_U0_ap_ready,
        m_axi_gmem_0_AWVALID => read_task_U0_m_axi_gmem_0_AWVALID,
        m_axi_gmem_0_AWREADY => ap_const_logic_0,
        m_axi_gmem_0_AWADDR => read_task_U0_m_axi_gmem_0_AWADDR,
        m_axi_gmem_0_AWID => read_task_U0_m_axi_gmem_0_AWID,
        m_axi_gmem_0_AWLEN => read_task_U0_m_axi_gmem_0_AWLEN,
        m_axi_gmem_0_AWSIZE => read_task_U0_m_axi_gmem_0_AWSIZE,
        m_axi_gmem_0_AWBURST => read_task_U0_m_axi_gmem_0_AWBURST,
        m_axi_gmem_0_AWLOCK => read_task_U0_m_axi_gmem_0_AWLOCK,
        m_axi_gmem_0_AWCACHE => read_task_U0_m_axi_gmem_0_AWCACHE,
        m_axi_gmem_0_AWPROT => read_task_U0_m_axi_gmem_0_AWPROT,
        m_axi_gmem_0_AWQOS => read_task_U0_m_axi_gmem_0_AWQOS,
        m_axi_gmem_0_AWREGION => read_task_U0_m_axi_gmem_0_AWREGION,
        m_axi_gmem_0_AWUSER => read_task_U0_m_axi_gmem_0_AWUSER,
        m_axi_gmem_0_WVALID => read_task_U0_m_axi_gmem_0_WVALID,
        m_axi_gmem_0_WREADY => ap_const_logic_0,
        m_axi_gmem_0_WDATA => read_task_U0_m_axi_gmem_0_WDATA,
        m_axi_gmem_0_WSTRB => read_task_U0_m_axi_gmem_0_WSTRB,
        m_axi_gmem_0_WLAST => read_task_U0_m_axi_gmem_0_WLAST,
        m_axi_gmem_0_WID => read_task_U0_m_axi_gmem_0_WID,
        m_axi_gmem_0_WUSER => read_task_U0_m_axi_gmem_0_WUSER,
        m_axi_gmem_0_ARVALID => read_task_U0_m_axi_gmem_0_ARVALID,
        m_axi_gmem_0_ARREADY => gmem_0_ARREADY,
        m_axi_gmem_0_ARADDR => read_task_U0_m_axi_gmem_0_ARADDR,
        m_axi_gmem_0_ARID => read_task_U0_m_axi_gmem_0_ARID,
        m_axi_gmem_0_ARLEN => read_task_U0_m_axi_gmem_0_ARLEN,
        m_axi_gmem_0_ARSIZE => read_task_U0_m_axi_gmem_0_ARSIZE,
        m_axi_gmem_0_ARBURST => read_task_U0_m_axi_gmem_0_ARBURST,
        m_axi_gmem_0_ARLOCK => read_task_U0_m_axi_gmem_0_ARLOCK,
        m_axi_gmem_0_ARCACHE => read_task_U0_m_axi_gmem_0_ARCACHE,
        m_axi_gmem_0_ARPROT => read_task_U0_m_axi_gmem_0_ARPROT,
        m_axi_gmem_0_ARQOS => read_task_U0_m_axi_gmem_0_ARQOS,
        m_axi_gmem_0_ARREGION => read_task_U0_m_axi_gmem_0_ARREGION,
        m_axi_gmem_0_ARUSER => read_task_U0_m_axi_gmem_0_ARUSER,
        m_axi_gmem_0_RVALID => gmem_0_RVALID,
        m_axi_gmem_0_RREADY => read_task_U0_m_axi_gmem_0_RREADY,
        m_axi_gmem_0_RDATA => gmem_0_RDATA,
        m_axi_gmem_0_RLAST => gmem_0_RLAST,
        m_axi_gmem_0_RID => gmem_0_RID,
        m_axi_gmem_0_RFIFONUM => gmem_0_RFIFONUM,
        m_axi_gmem_0_RUSER => gmem_0_RUSER,
        m_axi_gmem_0_RRESP => gmem_0_RRESP,
        m_axi_gmem_0_BVALID => ap_const_logic_0,
        m_axi_gmem_0_BREADY => read_task_U0_m_axi_gmem_0_BREADY,
        m_axi_gmem_0_BRESP => ap_const_lv2_0,
        m_axi_gmem_0_BID => ap_const_lv1_0,
        m_axi_gmem_0_BUSER => ap_const_lv1_0,
        in_r => in_r,
        input_r_address0 => read_task_U0_input_r_address0,
        input_r_ce0 => read_task_U0_input_r_ce0,
        input_r_we0 => read_task_U0_input_r_we0,
        input_r_d0 => read_task_U0_input_r_d0,
        N => N,
        ap_return => read_task_U0_ap_return);

    fir_U0 : component top_fir
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => fir_U0_ap_start,
        ap_done => fir_U0_ap_done,
        ap_continue => fir_U0_ap_continue,
        ap_idle => fir_U0_ap_idle,
        ap_ready => fir_U0_ap_ready,
        in_r_address0 => fir_U0_in_r_address0,
        in_r_ce0 => fir_U0_in_r_ce0,
        in_r_q0 => input_r_t_q0,
        out_r_address0 => fir_U0_out_r_address0,
        out_r_ce0 => fir_U0_out_r_ce0,
        out_r_we0 => fir_U0_out_r_we0,
        out_r_d0 => fir_U0_out_r_d0,
        p_read => N_c1_channel_dout,
        ap_return => fir_U0_ap_return);

    write_task_U0 : component top_write_task
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => write_task_U0_ap_start,
        ap_done => write_task_U0_ap_done,
        ap_continue => write_task_U0_ap_continue,
        ap_idle => write_task_U0_ap_idle,
        ap_ready => write_task_U0_ap_ready,
        output_r_address0 => write_task_U0_output_r_address0,
        output_r_ce0 => write_task_U0_output_r_ce0,
        output_r_q0 => output_r_t_q0,
        m_axi_gmem_0_AWVALID => write_task_U0_m_axi_gmem_0_AWVALID,
        m_axi_gmem_0_AWREADY => gmem_0_AWREADY,
        m_axi_gmem_0_AWADDR => write_task_U0_m_axi_gmem_0_AWADDR,
        m_axi_gmem_0_AWID => write_task_U0_m_axi_gmem_0_AWID,
        m_axi_gmem_0_AWLEN => write_task_U0_m_axi_gmem_0_AWLEN,
        m_axi_gmem_0_AWSIZE => write_task_U0_m_axi_gmem_0_AWSIZE,
        m_axi_gmem_0_AWBURST => write_task_U0_m_axi_gmem_0_AWBURST,
        m_axi_gmem_0_AWLOCK => write_task_U0_m_axi_gmem_0_AWLOCK,
        m_axi_gmem_0_AWCACHE => write_task_U0_m_axi_gmem_0_AWCACHE,
        m_axi_gmem_0_AWPROT => write_task_U0_m_axi_gmem_0_AWPROT,
        m_axi_gmem_0_AWQOS => write_task_U0_m_axi_gmem_0_AWQOS,
        m_axi_gmem_0_AWREGION => write_task_U0_m_axi_gmem_0_AWREGION,
        m_axi_gmem_0_AWUSER => write_task_U0_m_axi_gmem_0_AWUSER,
        m_axi_gmem_0_WVALID => write_task_U0_m_axi_gmem_0_WVALID,
        m_axi_gmem_0_WREADY => gmem_0_WREADY,
        m_axi_gmem_0_WDATA => write_task_U0_m_axi_gmem_0_WDATA,
        m_axi_gmem_0_WSTRB => write_task_U0_m_axi_gmem_0_WSTRB,
        m_axi_gmem_0_WLAST => write_task_U0_m_axi_gmem_0_WLAST,
        m_axi_gmem_0_WID => write_task_U0_m_axi_gmem_0_WID,
        m_axi_gmem_0_WUSER => write_task_U0_m_axi_gmem_0_WUSER,
        m_axi_gmem_0_ARVALID => write_task_U0_m_axi_gmem_0_ARVALID,
        m_axi_gmem_0_ARREADY => ap_const_logic_0,
        m_axi_gmem_0_ARADDR => write_task_U0_m_axi_gmem_0_ARADDR,
        m_axi_gmem_0_ARID => write_task_U0_m_axi_gmem_0_ARID,
        m_axi_gmem_0_ARLEN => write_task_U0_m_axi_gmem_0_ARLEN,
        m_axi_gmem_0_ARSIZE => write_task_U0_m_axi_gmem_0_ARSIZE,
        m_axi_gmem_0_ARBURST => write_task_U0_m_axi_gmem_0_ARBURST,
        m_axi_gmem_0_ARLOCK => write_task_U0_m_axi_gmem_0_ARLOCK,
        m_axi_gmem_0_ARCACHE => write_task_U0_m_axi_gmem_0_ARCACHE,
        m_axi_gmem_0_ARPROT => write_task_U0_m_axi_gmem_0_ARPROT,
        m_axi_gmem_0_ARQOS => write_task_U0_m_axi_gmem_0_ARQOS,
        m_axi_gmem_0_ARREGION => write_task_U0_m_axi_gmem_0_ARREGION,
        m_axi_gmem_0_ARUSER => write_task_U0_m_axi_gmem_0_ARUSER,
        m_axi_gmem_0_RVALID => ap_const_logic_0,
        m_axi_gmem_0_RREADY => write_task_U0_m_axi_gmem_0_RREADY,
        m_axi_gmem_0_RDATA => ap_const_lv256_lc_1,
        m_axi_gmem_0_RLAST => ap_const_logic_0,
        m_axi_gmem_0_RID => ap_const_lv1_0,
        m_axi_gmem_0_RFIFONUM => ap_const_lv9_0,
        m_axi_gmem_0_RUSER => ap_const_lv1_0,
        m_axi_gmem_0_RRESP => ap_const_lv2_0,
        m_axi_gmem_0_BVALID => gmem_0_BVALID,
        m_axi_gmem_0_BREADY => write_task_U0_m_axi_gmem_0_BREADY,
        m_axi_gmem_0_BRESP => gmem_0_BRESP,
        m_axi_gmem_0_BID => gmem_0_BID,
        m_axi_gmem_0_BUSER => gmem_0_BUSER,
        out_r_dout => out_r_c_dout,
        out_r_empty_n => out_r_c_empty_n,
        out_r_read => write_task_U0_out_r_read,
        out_r_num_data_valid => out_r_c_num_data_valid,
        out_r_fifo_cap => out_r_c_fifo_cap,
        p_read => N_c_channel_dout);

    out_r_c_U : component top_fifo_w64_d4_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_out_r_c_din,
        if_full_n => out_r_c_full_n,
        if_write => entry_proc_U0_out_r_c_write,
        if_dout => out_r_c_dout,
        if_empty_n => out_r_c_empty_n,
        if_read => write_task_U0_out_r_read,
        if_num_data_valid => out_r_c_num_data_valid,
        if_fifo_cap => out_r_c_fifo_cap);

    N_c1_channel_U : component top_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => read_task_U0_ap_return,
        if_full_n => N_c1_channel_full_n,
        if_write => ap_channel_done_N_c1_channel,
        if_dout => N_c1_channel_dout,
        if_empty_n => N_c1_channel_empty_n,
        if_read => fir_U0_ap_ready,
        if_num_data_valid => N_c1_channel_num_data_valid,
        if_fifo_cap => N_c1_channel_fifo_cap);

    N_c_channel_U : component top_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => fir_U0_ap_return,
        if_full_n => N_c_channel_full_n,
        if_write => ap_channel_done_N_c_channel,
        if_dout => N_c_channel_dout,
        if_empty_n => N_c_channel_empty_n,
        if_read => write_task_U0_ap_ready,
        if_num_data_valid => N_c_channel_num_data_valid,
        if_fifo_cap => N_c_channel_fifo_cap);





    ap_sync_reg_channel_write_N_c1_channel_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_N_c1_channel <= ap_const_logic_0;
            else
                if (((read_task_U0_ap_done and read_task_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_N_c1_channel <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_N_c1_channel <= ap_sync_channel_write_N_c1_channel;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_N_c_channel_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_N_c_channel <= ap_const_logic_0;
            else
                if (((fir_U0_ap_done and fir_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_N_c_channel <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_N_c_channel <= ap_sync_channel_write_N_c_channel;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_input_r_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_input_r <= ap_const_logic_0;
            else
                if (((read_task_U0_ap_done and read_task_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_input_r <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_input_r <= ap_sync_channel_write_input_r;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_output_r_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_output_r <= ap_const_logic_0;
            else
                if (((fir_U0_ap_done and fir_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_output_r <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_output_r <= ap_sync_channel_write_output_r;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_entry_proc_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_entry_proc_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_entry_proc_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_read_task_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_read_task_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_read_task_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_read_task_U0_ap_ready <= ap_sync_read_task_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_rst_n_inv_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_n_inv <= ap_rst_reg_1;
        end if;
    end process;

    ap_rst_reg_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_reg_1 <= ap_rst_reg_2;
        end if;
    end process;

    ap_rst_reg_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
                        ap_rst_reg_2 <= not(ap_rst_n);
        end if;
    end process;
    ap_channel_done_N_c1_channel <= (read_task_U0_ap_done and (ap_sync_reg_channel_write_N_c1_channel xor ap_const_logic_1));
    ap_channel_done_N_c_channel <= (fir_U0_ap_done and (ap_sync_reg_channel_write_N_c_channel xor ap_const_logic_1));
    ap_channel_done_input_r <= (read_task_U0_ap_done and (ap_sync_reg_channel_write_input_r xor ap_const_logic_1));
    ap_channel_done_output_r <= (fir_U0_ap_done and (ap_sync_reg_channel_write_output_r xor ap_const_logic_1));
    ap_done <= write_task_U0_ap_done;
    ap_idle <= (write_task_U0_ap_idle and read_task_U0_ap_idle and fir_U0_ap_idle and (ap_const_logic_1 xor N_c_channel_empty_n) and (ap_const_logic_1 xor N_c1_channel_empty_n) and entry_proc_U0_ap_idle);
    ap_ready <= ap_sync_ready;
    ap_sync_channel_write_N_c1_channel <= ((ap_channel_done_N_c1_channel and N_c1_channel_full_n) or ap_sync_reg_channel_write_N_c1_channel);
    ap_sync_channel_write_N_c_channel <= ((ap_channel_done_N_c_channel and N_c_channel_full_n) or ap_sync_reg_channel_write_N_c_channel);
    ap_sync_channel_write_input_r <= ((read_task_U0_input_r_full_n and ap_channel_done_input_r) or ap_sync_reg_channel_write_input_r);
    ap_sync_channel_write_output_r <= ((fir_U0_out_r_full_n and ap_channel_done_output_r) or ap_sync_reg_channel_write_output_r);
    ap_sync_entry_proc_U0_ap_ready <= (entry_proc_U0_ap_ready or ap_sync_reg_entry_proc_U0_ap_ready);
    ap_sync_read_task_U0_ap_ready <= (read_task_U0_ap_ready or ap_sync_reg_read_task_U0_ap_ready);
    ap_sync_ready <= (ap_sync_read_task_U0_ap_ready and ap_sync_entry_proc_U0_ap_ready);
    entry_proc_U0_ap_continue <= ap_const_logic_1;
    entry_proc_U0_ap_start <= ((ap_sync_reg_entry_proc_U0_ap_ready xor ap_const_logic_1) and ap_start);
    fir_U0_ap_continue <= ap_sync_channel_write_output_r;
    fir_U0_ap_start <= N_c1_channel_empty_n;
    fir_U0_out_r_full_n <= output_r_i_full_n;
    gmem_0_BID <= ap_const_lv1_0;
    gmem_0_BRESP <= ap_const_lv2_0;
    gmem_0_BUSER <= ap_const_lv1_0;
    gmem_0_RID <= ap_const_lv1_0;
    gmem_0_RLAST <= ap_const_logic_0;
    gmem_0_RRESP <= ap_const_lv2_0;
    gmem_0_RUSER <= ap_const_lv1_0;
    read_task_U0_ap_continue <= ap_sync_channel_write_input_r;
    read_task_U0_ap_start <= ((ap_sync_reg_read_task_U0_ap_ready xor ap_const_logic_1) and ap_start);
    read_task_U0_input_r_full_n <= input_r_i_full_n;
    write_task_U0_ap_continue <= ap_continue;
    write_task_U0_ap_start <= N_c_channel_empty_n;
end behav;
